### PR TITLE
Changed the C# V1 benchmarks to use structs instead of classes

### PR DESCRIPTION
**Pull request by initram**
This should reduce pointer chasing and should make the implementation more comparable to the the C++ implementation. It should also increase the performance of these benchmarks.

I have not been able to run the benchmarks to see the difference, as i currently work on Windows.

### CODE REVIEW

**Comment by cart** [comment]
Thanks for the contribution! I'll take a look after work today. While in theory I think you're right, in practice i think the stack vs heap issue is nuanced / optimized by the runtime. Its possible we won't see much of a difference.

But who knows? Only one way to find out 😄

**Comment by cart** [comment]
Well this is unexpected. I'm consistently seeing lower results with structs by ~1000 bunnies. I expected an increase of something between 0 and SMALL_NUMBER here. But a decrease is very odd.

I'll leave this open for a bit to see if anyone else can see different results, but otherwise I will close this out because it appears to be a downgrade.

**Comment by Trayani** [comment]
That is weird. What about changing 
`var bunny = bunnies[i];`
to
`ref var bunny = ref bunnies[i];`
?

With Unsafe.Add, we could also optimize iterations, but not I'm sure if it is possible with Mono+Godot atm.

**Comment by initram** [comment]
I am unable to take a reference to the bunny from the list, as list does not support ref indexing. I guess I could change it to an array, then I could take a reference. That would require more book-keeping though to track how many elements are in the array and when to reallocate the array if it fills up.

**Comment by initram** [comment]
I have now changed the list to array, to be able to take a reference into the collection of bunnies. If this does not improve performance, then I will close this pull request.

**Pull request closed without merging**
